language: cpp
sudo: required
dist: xenial

compiler:
    - gcc
    - clang

env:
    -
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release

cache:
  directories:
    boost-cache

script:
    - mkdir boost-cache build.tmp && cd build.tmp
    - git clone https://github.com/KayEss/fost-boost.git
    - ln -s ../boost-cache fost-boost/boost
    - cd fost-boost && cmake . && cd ..
    - cmake .. -DCMAKE_CXX_FLAGS="-I$(pwd)/fost-boost/boost/1_66_0/$CC/$(echo $CMAKE_BUILD_TYPE | s/Debug/debug/ | sed s/Release/release/)/"
    - make -n
    - make -n check
