language: cpp
sudo: required
dist: xenial

compiler:
    - gcc
    - clang

env:
    -
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release

script:
    - mkdir build.tmp && cd build.tmp
    - git clone -b boost-1.63.0 git@github.com:boostorg/asio.git
    - cmake .. -DCMAKE_CXX_FLAGS=-Iasio/include
    - make
    - make check

