language: cpp
sudo: required
dist: xenial

compiler:
    - gcc
    - clang

env:
    -
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release

script:
    - apt install -y -qq boost-dev-all
    - mkdir build.tmp && cd build.tmp
    - cmake ..
    - make
    - make check

