language: cpp
sudo: required
dist: artful

compiler:
    - gcc
    - clang

env:
    -
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release

script:
    - sudo apt install -y -qq libboost-all-dev
    - mkdir build.tmp && cd build.tmp
    - cmake ..
    - make
    - make check

