language: cpp
sudo: required
dist: xenial

compiler:
    - gcc
    - clang

env:
    -
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release

script:
    - mkdir build.tmp && cd build.tmp
    - git clone https://github.com/KayEss/fost-boost.git
    - cmake -C fost-boost
    - cmake .. -DCMAKE_CXX_FLAGS="-I$(pwd)/fost-boost/boost/1_62_0/$CC/$(echo CMAKE_BUILD_TYPE | s/Debug/debug/ | sed s/Release/release/)/"
    - make
    - make check

